sudo: required
dist: trusty
before_install: ./.travis_native_dependencies.sh
before_script:
  - pip2.7 install --upgrade --ignore-installed --user jsontree asttokens
  - export PATH=$PWD/srcML-src/bin:$PATH
  - export PATH=$PWD/cgum:$PATH
  - export PATH=$PWD/pythonparser:$PATH
script: ./gradlew check
after_success:
  - ./gradlew coveralls uploadArchives
language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  skip_cleanup: true
  on:
    branch: master
    tags: true
  file: dist/build/distributions/gumtree.zip
  api_key:
    secure: KDxVpvCTWmZK2Nxa879vjP1OCWwI5qU2BSGf9fSb/d1SiBAlFZL9AB5FTpo1JBmfTXhhk4K3YrK2d5CtDs2CmAv2s1CNDQ7RaaZXlr1ApSS/UlhNNNEFwMTkL0ZiWz54/mQW812V6KbZPOf2XxO3fns+mN43x/8PYQn8mfBDxok=
