# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TypeGraph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TypeNode_pb2 as TypeNode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TypeGraph.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\031com.t2r.common.models.ast',
  serialized_pb=b'\n\x0fTypeGraph.proto\x1a\x0eTypeNode.proto\"\x84\x01\n\tTypeGraph\x12\x17\n\x04root\x18\x01 \x01(\x0b\x32\t.TypeNode\x12$\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x15.TypeGraph.EdgesEntry\x1a\x38\n\nEdgesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.TypeGraph:\x02\x38\x01\x42\x1b\n\x19\x63om.t2r.common.models.astb\x06proto3'
  ,
  dependencies=[TypeNode__pb2.DESCRIPTOR,])




_TYPEGRAPH_EDGESENTRY = _descriptor.Descriptor(
  name='EdgesEntry',
  full_name='TypeGraph.EdgesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TypeGraph.EdgesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TypeGraph.EdgesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=168,
)

_TYPEGRAPH = _descriptor.Descriptor(
  name='TypeGraph',
  full_name='TypeGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='TypeGraph.root', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='edges', full_name='TypeGraph.edges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TYPEGRAPH_EDGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=168,
)

_TYPEGRAPH_EDGESENTRY.fields_by_name['value'].message_type = _TYPEGRAPH
_TYPEGRAPH_EDGESENTRY.containing_type = _TYPEGRAPH
_TYPEGRAPH.fields_by_name['root'].message_type = TypeNode__pb2._TYPENODE
_TYPEGRAPH.fields_by_name['edges'].message_type = _TYPEGRAPH_EDGESENTRY
DESCRIPTOR.message_types_by_name['TypeGraph'] = _TYPEGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeGraph = _reflection.GeneratedProtocolMessageType('TypeGraph', (_message.Message,), {

  'EdgesEntry' : _reflection.GeneratedProtocolMessageType('EdgesEntry', (_message.Message,), {
    'DESCRIPTOR' : _TYPEGRAPH_EDGESENTRY,
    '__module__' : 'TypeGraph_pb2'
    # @@protoc_insertion_point(class_scope:TypeGraph.EdgesEntry)
    })
  ,
  'DESCRIPTOR' : _TYPEGRAPH,
  '__module__' : 'TypeGraph_pb2'
  # @@protoc_insertion_point(class_scope:TypeGraph)
  })
_sym_db.RegisterMessage(TypeGraph)
_sym_db.RegisterMessage(TypeGraph.EdgesEntry)


DESCRIPTOR._options = None
_TYPEGRAPH_EDGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
