# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DependencyUpdate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import JarInfo_pb2 as JarInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DependencyUpdate.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"com.t2r.common.models.refactorings',
  serialized_pb=b'\n\x16\x44\x65pendencyUpdate.proto\x1a\rJarInfo.proto\"g\n\x10\x44\x65pendencyUpdate\x12\x1f\n\x06update\x18\x03 \x03(\x0b\x32\x0f.DependencyPair\x12\x17\n\x05\x61\x64\x64\x65\x64\x18\x01 \x03(\x0b\x32\x08.JarInfo\x12\x19\n\x07removed\x18\x02 \x03(\x0b\x32\x08.JarInfo\"C\n\x0e\x44\x65pendencyPair\x12\x18\n\x06\x62\x65\x66ore\x18\x01 \x01(\x0b\x32\x08.JarInfo\x12\x17\n\x05\x61\x66ter\x18\x02 \x01(\x0b\x32\x08.JarInfoB$\n\"com.t2r.common.models.refactoringsb\x06proto3'
  ,
  dependencies=[JarInfo__pb2.DESCRIPTOR,])




_DEPENDENCYUPDATE = _descriptor.Descriptor(
  name='DependencyUpdate',
  full_name='DependencyUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='update', full_name='DependencyUpdate.update', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='added', full_name='DependencyUpdate.added', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='removed', full_name='DependencyUpdate.removed', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=144,
)


_DEPENDENCYPAIR = _descriptor.Descriptor(
  name='DependencyPair',
  full_name='DependencyPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='before', full_name='DependencyPair.before', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after', full_name='DependencyPair.after', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=213,
)

_DEPENDENCYUPDATE.fields_by_name['update'].message_type = _DEPENDENCYPAIR
_DEPENDENCYUPDATE.fields_by_name['added'].message_type = JarInfo__pb2._JARINFO
_DEPENDENCYUPDATE.fields_by_name['removed'].message_type = JarInfo__pb2._JARINFO
_DEPENDENCYPAIR.fields_by_name['before'].message_type = JarInfo__pb2._JARINFO
_DEPENDENCYPAIR.fields_by_name['after'].message_type = JarInfo__pb2._JARINFO
DESCRIPTOR.message_types_by_name['DependencyUpdate'] = _DEPENDENCYUPDATE
DESCRIPTOR.message_types_by_name['DependencyPair'] = _DEPENDENCYPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DependencyUpdate = _reflection.GeneratedProtocolMessageType('DependencyUpdate', (_message.Message,), {
  'DESCRIPTOR' : _DEPENDENCYUPDATE,
  '__module__' : 'DependencyUpdate_pb2'
  # @@protoc_insertion_point(class_scope:DependencyUpdate)
  })
_sym_db.RegisterMessage(DependencyUpdate)

DependencyPair = _reflection.GeneratedProtocolMessageType('DependencyPair', (_message.Message,), {
  'DESCRIPTOR' : _DEPENDENCYPAIR,
  '__module__' : 'DependencyUpdate_pb2'
  # @@protoc_insertion_point(class_scope:DependencyPair)
  })
_sym_db.RegisterMessage(DependencyPair)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
