# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameSpace.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NameSpace.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"com.t2r.common.models.refactorings',
  serialized_pb=b'\n\x0fNameSpace.proto*P\n\tNameSpace\x12\x10\n\x0cTypeVariable\x10\x00\x12\x07\n\x03Jdk\x10\x02\x12\x0c\n\x08\x45xternal\x10\x03\x12\x0c\n\x08Internal\x10\x04\x12\x0c\n\x08\x44ontKnow\x10\x05\x42$\n\"com.t2r.common.models.refactoringsb\x06proto3'
)

_NAMESPACE = _descriptor.EnumDescriptor(
  name='NameSpace',
  full_name='NameSpace',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TypeVariable', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Jdk', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='External', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Internal', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DontKnow', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=19,
  serialized_end=99,
)
_sym_db.RegisterEnumDescriptor(_NAMESPACE)

NameSpace = enum_type_wrapper.EnumTypeWrapper(_NAMESPACE)
TypeVariable = 0
Jdk = 2
External = 3
Internal = 4
DontKnow = 5


DESCRIPTOR.enum_types_by_name['NameSpace'] = _NAMESPACE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
