# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProcessedCodeMappings.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TypeGraph_pb2 as TypeGraph__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProcessedCodeMappings.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"com.t2r.common.models.refactorings',
  serialized_pb=b'\n\x1bProcessedCodeMappings.proto\x1a\x0fTypeGraph.proto\"\xdf\x02\n\x15ProcessedCodeMappings\x12\x16\n\x02\x62\x34\x18\x03 \x01(\x0b\x32\n.TypeGraph\x12\x18\n\x04\x61\x66tr\x18\x02 \x01(\x0b\x32\n.TypeGraph\x12\x41\n\rrelevantStmts\x18\x01 \x03(\x0b\x32*.ProcessedCodeMappings.RelevantStmtMapping\x1a\x8c\x01\n\x13RelevantStmtMapping\x12\n\n\x02\x62\x34\x18\x01 \x01(\t\x12\r\n\x05\x61\x66ter\x18\x02 \x01(\t\x12\x39\n\x07mapping\x18\x03 \x03(\x0b\x32(.ProcessedCodeMappings.ExpressionMapping\x12\x0e\n\x06urlbB4\x18\x06 \x01(\t\x12\x0f\n\x07urlAftr\x18\x05 \x01(\t\x1a\x42\n\x11\x45xpressionMapping\x12\x13\n\x0breplacement\x18\x04 \x01(\t\x12\n\n\x02\x62\x34\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x66tr\x18\x02 \x01(\tB$\n\"com.t2r.common.models.refactoringsb\x06proto3'
  ,
  dependencies=[TypeGraph__pb2.DESCRIPTOR,])




_PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING = _descriptor.Descriptor(
  name='RelevantStmtMapping',
  full_name='ProcessedCodeMappings.RelevantStmtMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b4', full_name='ProcessedCodeMappings.RelevantStmtMapping.b4', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='after', full_name='ProcessedCodeMappings.RelevantStmtMapping.after', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapping', full_name='ProcessedCodeMappings.RelevantStmtMapping.mapping', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urlbB4', full_name='ProcessedCodeMappings.RelevantStmtMapping.urlbB4', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urlAftr', full_name='ProcessedCodeMappings.RelevantStmtMapping.urlAftr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=332,
)

_PROCESSEDCODEMAPPINGS_EXPRESSIONMAPPING = _descriptor.Descriptor(
  name='ExpressionMapping',
  full_name='ProcessedCodeMappings.ExpressionMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replacement', full_name='ProcessedCodeMappings.ExpressionMapping.replacement', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b4', full_name='ProcessedCodeMappings.ExpressionMapping.b4', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aftr', full_name='ProcessedCodeMappings.ExpressionMapping.aftr', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=400,
)

_PROCESSEDCODEMAPPINGS = _descriptor.Descriptor(
  name='ProcessedCodeMappings',
  full_name='ProcessedCodeMappings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b4', full_name='ProcessedCodeMappings.b4', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aftr', full_name='ProcessedCodeMappings.aftr', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relevantStmts', full_name='ProcessedCodeMappings.relevantStmts', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING, _PROCESSEDCODEMAPPINGS_EXPRESSIONMAPPING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=400,
)

_PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING.fields_by_name['mapping'].message_type = _PROCESSEDCODEMAPPINGS_EXPRESSIONMAPPING
_PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING.containing_type = _PROCESSEDCODEMAPPINGS
_PROCESSEDCODEMAPPINGS_EXPRESSIONMAPPING.containing_type = _PROCESSEDCODEMAPPINGS
_PROCESSEDCODEMAPPINGS.fields_by_name['b4'].message_type = TypeGraph__pb2._TYPEGRAPH
_PROCESSEDCODEMAPPINGS.fields_by_name['aftr'].message_type = TypeGraph__pb2._TYPEGRAPH
_PROCESSEDCODEMAPPINGS.fields_by_name['relevantStmts'].message_type = _PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING
DESCRIPTOR.message_types_by_name['ProcessedCodeMappings'] = _PROCESSEDCODEMAPPINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessedCodeMappings = _reflection.GeneratedProtocolMessageType('ProcessedCodeMappings', (_message.Message,), {

  'RelevantStmtMapping' : _reflection.GeneratedProtocolMessageType('RelevantStmtMapping', (_message.Message,), {
    'DESCRIPTOR' : _PROCESSEDCODEMAPPINGS_RELEVANTSTMTMAPPING,
    '__module__' : 'ProcessedCodeMappings_pb2'
    # @@protoc_insertion_point(class_scope:ProcessedCodeMappings.RelevantStmtMapping)
    })
  ,

  'ExpressionMapping' : _reflection.GeneratedProtocolMessageType('ExpressionMapping', (_message.Message,), {
    'DESCRIPTOR' : _PROCESSEDCODEMAPPINGS_EXPRESSIONMAPPING,
    '__module__' : 'ProcessedCodeMappings_pb2'
    # @@protoc_insertion_point(class_scope:ProcessedCodeMappings.ExpressionMapping)
    })
  ,
  'DESCRIPTOR' : _PROCESSEDCODEMAPPINGS,
  '__module__' : 'ProcessedCodeMappings_pb2'
  # @@protoc_insertion_point(class_scope:ProcessedCodeMappings)
  })
_sym_db.RegisterMessage(ProcessedCodeMappings)
_sym_db.RegisterMessage(ProcessedCodeMappings.RelevantStmtMapping)
_sym_db.RegisterMessage(ProcessedCodeMappings.ExpressionMapping)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
