# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TheWorld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TheWorld.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"com.t2r.common.models.refactorings',
  serialized_pb=b'\n\x0eTheWorld.proto\"\xbd\x03\n\x08TheWorld\x12\x0b\n\x03sha\x18\x05 \x01(\t\x12\x33\n\rvisibilityMap\x18\x01 \x03(\x0b\x32\x1c.TheWorld.VisibilityMapEntry\x12/\n\x0btypeKindMap\x18\x02 \x03(\x0b\x32\x1a.TheWorld.TypeKindMapEntry\x12\x31\n\x0cnameSpaceMap\x18\x03 \x03(\x0b\x32\x1b.TheWorld.NameSpaceMapEntry\x12\x35\n\x0e\x65lementKindMap\x18\x04 \x03(\x0b\x32\x1d.TheWorld.ElementKindMapEntry\x1a\x34\n\x12VisibilityMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10TypeKindMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x33\n\x11NameSpaceMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x35\n\x13\x45lementKindMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42$\n\"com.t2r.common.models.refactoringsb\x06proto3'
)




_THEWORLD_VISIBILITYMAPENTRY = _descriptor.Descriptor(
  name='VisibilityMapEntry',
  full_name='TheWorld.VisibilityMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TheWorld.VisibilityMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TheWorld.VisibilityMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=304,
)

_THEWORLD_TYPEKINDMAPENTRY = _descriptor.Descriptor(
  name='TypeKindMapEntry',
  full_name='TheWorld.TypeKindMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TheWorld.TypeKindMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TheWorld.TypeKindMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=356,
)

_THEWORLD_NAMESPACEMAPENTRY = _descriptor.Descriptor(
  name='NameSpaceMapEntry',
  full_name='TheWorld.NameSpaceMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TheWorld.NameSpaceMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TheWorld.NameSpaceMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=409,
)

_THEWORLD_ELEMENTKINDMAPENTRY = _descriptor.Descriptor(
  name='ElementKindMapEntry',
  full_name='TheWorld.ElementKindMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TheWorld.ElementKindMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TheWorld.ElementKindMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=464,
)

_THEWORLD = _descriptor.Descriptor(
  name='TheWorld',
  full_name='TheWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha', full_name='TheWorld.sha', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibilityMap', full_name='TheWorld.visibilityMap', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typeKindMap', full_name='TheWorld.typeKindMap', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nameSpaceMap', full_name='TheWorld.nameSpaceMap', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elementKindMap', full_name='TheWorld.elementKindMap', index=4,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_THEWORLD_VISIBILITYMAPENTRY, _THEWORLD_TYPEKINDMAPENTRY, _THEWORLD_NAMESPACEMAPENTRY, _THEWORLD_ELEMENTKINDMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=464,
)

_THEWORLD_VISIBILITYMAPENTRY.containing_type = _THEWORLD
_THEWORLD_TYPEKINDMAPENTRY.containing_type = _THEWORLD
_THEWORLD_NAMESPACEMAPENTRY.containing_type = _THEWORLD
_THEWORLD_ELEMENTKINDMAPENTRY.containing_type = _THEWORLD
_THEWORLD.fields_by_name['visibilityMap'].message_type = _THEWORLD_VISIBILITYMAPENTRY
_THEWORLD.fields_by_name['typeKindMap'].message_type = _THEWORLD_TYPEKINDMAPENTRY
_THEWORLD.fields_by_name['nameSpaceMap'].message_type = _THEWORLD_NAMESPACEMAPENTRY
_THEWORLD.fields_by_name['elementKindMap'].message_type = _THEWORLD_ELEMENTKINDMAPENTRY
DESCRIPTOR.message_types_by_name['TheWorld'] = _THEWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TheWorld = _reflection.GeneratedProtocolMessageType('TheWorld', (_message.Message,), {

  'VisibilityMapEntry' : _reflection.GeneratedProtocolMessageType('VisibilityMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _THEWORLD_VISIBILITYMAPENTRY,
    '__module__' : 'TheWorld_pb2'
    # @@protoc_insertion_point(class_scope:TheWorld.VisibilityMapEntry)
    })
  ,

  'TypeKindMapEntry' : _reflection.GeneratedProtocolMessageType('TypeKindMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _THEWORLD_TYPEKINDMAPENTRY,
    '__module__' : 'TheWorld_pb2'
    # @@protoc_insertion_point(class_scope:TheWorld.TypeKindMapEntry)
    })
  ,

  'NameSpaceMapEntry' : _reflection.GeneratedProtocolMessageType('NameSpaceMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _THEWORLD_NAMESPACEMAPENTRY,
    '__module__' : 'TheWorld_pb2'
    # @@protoc_insertion_point(class_scope:TheWorld.NameSpaceMapEntry)
    })
  ,

  'ElementKindMapEntry' : _reflection.GeneratedProtocolMessageType('ElementKindMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _THEWORLD_ELEMENTKINDMAPENTRY,
    '__module__' : 'TheWorld_pb2'
    # @@protoc_insertion_point(class_scope:TheWorld.ElementKindMapEntry)
    })
  ,
  'DESCRIPTOR' : _THEWORLD,
  '__module__' : 'TheWorld_pb2'
  # @@protoc_insertion_point(class_scope:TheWorld)
  })
_sym_db.RegisterMessage(TheWorld)
_sym_db.RegisterMessage(TheWorld.VisibilityMapEntry)
_sym_db.RegisterMessage(TheWorld.TypeKindMapEntry)
_sym_db.RegisterMessage(TheWorld.NameSpaceMapEntry)
_sym_db.RegisterMessage(TheWorld.ElementKindMapEntry)


DESCRIPTOR._options = None
_THEWORLD_VISIBILITYMAPENTRY._options = None
_THEWORLD_TYPEKINDMAPENTRY._options = None
_THEWORLD_NAMESPACEMAPENTRY._options = None
_THEWORLD_ELEMENTKINDMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
