# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TypeNode.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TypeNode.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\031com.t2r.common.models.ast',
  serialized_pb=b'\n\x0eTypeNode.proto\"\xd6\x01\n\x08TypeNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12 \n\x04kind\x18\x02 \x01(\x0e\x32\x12.TypeNode.TypeKind\x12\x12\n\nisResolved\x18\x03 \x01(\x08\x12\x16\n\x0eisTypeVariable\x18\x04 \x01(\x08\"n\n\x08TypeKind\x12\n\n\x06Simple\x10\x00\x12\x11\n\rParameterized\x10\x02\x12\x0c\n\x08WildCard\x10\x03\x12\t\n\x05Union\x10\x04\x12\r\n\tPrimitive\x10\x05\x12\x10\n\x0cIntersection\x10\x06\x12\t\n\x05\x41rray\x10\x07\x42\x1b\n\x19\x63om.t2r.common.models.astb\x06proto3'
)



_TYPENODE_TYPEKIND = _descriptor.EnumDescriptor(
  name='TypeKind',
  full_name='TypeNode.TypeKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Simple', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Parameterized', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WildCard', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Union', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Primitive', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Intersection', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Array', index=6, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=123,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_TYPENODE_TYPEKIND)


_TYPENODE = _descriptor.Descriptor(
  name='TypeNode',
  full_name='TypeNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TypeNode.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='TypeNode.kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isResolved', full_name='TypeNode.isResolved', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isTypeVariable', full_name='TypeNode.isTypeVariable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TYPENODE_TYPEKIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=233,
)

_TYPENODE.fields_by_name['kind'].enum_type = _TYPENODE_TYPEKIND
_TYPENODE_TYPEKIND.containing_type = _TYPENODE
DESCRIPTOR.message_types_by_name['TypeNode'] = _TYPENODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeNode = _reflection.GeneratedProtocolMessageType('TypeNode', (_message.Message,), {
  'DESCRIPTOR' : _TYPENODE,
  '__module__' : 'TypeNode_pb2'
  # @@protoc_insertion_point(class_scope:TypeNode)
  })
_sym_db.RegisterMessage(TypeNode)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
