// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Identification.proto

package com.t2r.common.models.ast;

public final class IdentificationOuterClass {
  private IdentificationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Identification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.TypeSignature type = 2;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>.TypeSignature type = 2;</code>
     * @return The type.
     */
    com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature getType();
    /**
     * <code>.TypeSignature type = 2;</code>
     */
    com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder getTypeOrBuilder();

    /**
     * <code>.Identification owner = 3;</code>
     * @return Whether the owner field is set.
     */
    boolean hasOwner();
    /**
     * <code>.Identification owner = 3;</code>
     * @return The owner.
     */
    com.t2r.common.models.ast.IdentificationOuterClass.Identification getOwner();
    /**
     * <code>.Identification owner = 3;</code>
     */
    com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getOwnerOrBuilder();

    /**
     * <pre>
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     * </pre>
     *
     * <code>string kind = 4;</code>
     * @return The kind.
     */
    java.lang.String getKind();
    /**
     * <pre>
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     * </pre>
     *
     * <code>string kind = 4;</code>
     * @return The bytes for kind.
     */
    com.google.protobuf.ByteString
        getKindBytes();
  }
  /**
   * Protobuf type {@code Identification}
   */
  public  static final class Identification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Identification)
      IdentificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Identification.newBuilder() to construct.
    private Identification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Identification() {
      name_ = "";
      kind_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Identification();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Identification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder subBuilder = null;
              if (type_ != null) {
                subBuilder = type_.toBuilder();
              }
              type_ = input.readMessage(com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(type_);
                type_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder subBuilder = null;
              if (owner_ != null) {
                subBuilder = owner_.toBuilder();
              }
              owner_ = input.readMessage(com.t2r.common.models.ast.IdentificationOuterClass.Identification.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(owner_);
                owner_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              kind_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.ast.IdentificationOuterClass.internal_static_Identification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.ast.IdentificationOuterClass.internal_static_Identification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.ast.IdentificationOuterClass.Identification.class, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature type_;
    /**
     * <code>.TypeSignature type = 2;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return type_ != null;
    }
    /**
     * <code>.TypeSignature type = 2;</code>
     * @return The type.
     */
    public com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature getType() {
      return type_ == null ? com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.getDefaultInstance() : type_;
    }
    /**
     * <code>.TypeSignature type = 2;</code>
     */
    public com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder getTypeOrBuilder() {
      return getType();
    }

    public static final int OWNER_FIELD_NUMBER = 3;
    private com.t2r.common.models.ast.IdentificationOuterClass.Identification owner_;
    /**
     * <code>.Identification owner = 3;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return owner_ != null;
    }
    /**
     * <code>.Identification owner = 3;</code>
     * @return The owner.
     */
    public com.t2r.common.models.ast.IdentificationOuterClass.Identification getOwner() {
      return owner_ == null ? com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance() : owner_;
    }
    /**
     * <code>.Identification owner = 3;</code>
     */
    public com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getOwnerOrBuilder() {
      return getOwner();
    }

    public static final int KIND_FIELD_NUMBER = 4;
    private volatile java.lang.Object kind_;
    /**
     * <pre>
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     * </pre>
     *
     * <code>string kind = 4;</code>
     * @return The kind.
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
     * </pre>
     *
     * <code>string kind = 4;</code>
     * @return The bytes for kind.
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (type_ != null) {
        output.writeMessage(2, getType());
      }
      if (owner_ != null) {
        output.writeMessage(3, getOwner());
      }
      if (!getKindBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, kind_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (type_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getType());
      }
      if (owner_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOwner());
      }
      if (!getKindBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, kind_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.ast.IdentificationOuterClass.Identification)) {
        return super.equals(obj);
      }
      com.t2r.common.models.ast.IdentificationOuterClass.Identification other = (com.t2r.common.models.ast.IdentificationOuterClass.Identification) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasOwner() != other.hasOwner()) return false;
      if (hasOwner()) {
        if (!getOwner()
            .equals(other.getOwner())) return false;
      }
      if (!getKind()
          .equals(other.getKind())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasOwner()) {
        hash = (37 * hash) + OWNER_FIELD_NUMBER;
        hash = (53 * hash) + getOwner().hashCode();
      }
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + getKind().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.ast.IdentificationOuterClass.Identification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Identification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Identification)
        com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.ast.IdentificationOuterClass.internal_static_Identification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.ast.IdentificationOuterClass.internal_static_Identification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.ast.IdentificationOuterClass.Identification.class, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder.class);
      }

      // Construct using com.t2r.common.models.ast.IdentificationOuterClass.Identification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (typeBuilder_ == null) {
          type_ = null;
        } else {
          type_ = null;
          typeBuilder_ = null;
        }
        if (ownerBuilder_ == null) {
          owner_ = null;
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }
        kind_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.ast.IdentificationOuterClass.internal_static_Identification_descriptor;
      }

      @java.lang.Override
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification getDefaultInstanceForType() {
        return com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance();
      }

      @java.lang.Override
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification build() {
        com.t2r.common.models.ast.IdentificationOuterClass.Identification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification buildPartial() {
        com.t2r.common.models.ast.IdentificationOuterClass.Identification result = new com.t2r.common.models.ast.IdentificationOuterClass.Identification(this);
        result.name_ = name_;
        if (typeBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        if (ownerBuilder_ == null) {
          result.owner_ = owner_;
        } else {
          result.owner_ = ownerBuilder_.build();
        }
        result.kind_ = kind_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.ast.IdentificationOuterClass.Identification) {
          return mergeFrom((com.t2r.common.models.ast.IdentificationOuterClass.Identification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.ast.IdentificationOuterClass.Identification other) {
        if (other == com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          mergeType(other.getType());
        }
        if (other.hasOwner()) {
          mergeOwner(other.getOwner());
        }
        if (!other.getKind().isEmpty()) {
          kind_ = other.kind_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.ast.IdentificationOuterClass.Identification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.ast.IdentificationOuterClass.Identification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature type_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder> typeBuilder_;
      /**
       * <code>.TypeSignature type = 2;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return typeBuilder_ != null || type_ != null;
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       * @return The type.
       */
      public com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature getType() {
        if (typeBuilder_ == null) {
          return type_ == null ? com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.getDefaultInstance() : type_;
        } else {
          return typeBuilder_.getMessage();
        }
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public Builder setType(com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public Builder setType(
          com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder builderForValue) {
        if (typeBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public Builder mergeType(com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature value) {
        if (typeBuilder_ == null) {
          if (type_ != null) {
            type_ =
              com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.newBuilder(type_).mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          typeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = null;
          onChanged();
        } else {
          type_ = null;
          typeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder getTypeBuilder() {
        
        onChanged();
        return getTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      public com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder getTypeOrBuilder() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilder();
        } else {
          return type_ == null ?
              com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.getDefaultInstance() : type_;
        }
      }
      /**
       * <code>.TypeSignature type = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignature.Builder, com.t2r.common.models.ast.TypeSignatureOuterClass.TypeSignatureOrBuilder>(
                  getType(),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }

      private com.t2r.common.models.ast.IdentificationOuterClass.Identification owner_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> ownerBuilder_;
      /**
       * <code>.Identification owner = 3;</code>
       * @return Whether the owner field is set.
       */
      public boolean hasOwner() {
        return ownerBuilder_ != null || owner_ != null;
      }
      /**
       * <code>.Identification owner = 3;</code>
       * @return The owner.
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification getOwner() {
        if (ownerBuilder_ == null) {
          return owner_ == null ? com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance() : owner_;
        } else {
          return ownerBuilder_.getMessage();
        }
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public Builder setOwner(com.t2r.common.models.ast.IdentificationOuterClass.Identification value) {
        if (ownerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          owner_ = value;
          onChanged();
        } else {
          ownerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public Builder setOwner(
          com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder builderForValue) {
        if (ownerBuilder_ == null) {
          owner_ = builderForValue.build();
          onChanged();
        } else {
          ownerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public Builder mergeOwner(com.t2r.common.models.ast.IdentificationOuterClass.Identification value) {
        if (ownerBuilder_ == null) {
          if (owner_ != null) {
            owner_ =
              com.t2r.common.models.ast.IdentificationOuterClass.Identification.newBuilder(owner_).mergeFrom(value).buildPartial();
          } else {
            owner_ = value;
          }
          onChanged();
        } else {
          ownerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public Builder clearOwner() {
        if (ownerBuilder_ == null) {
          owner_ = null;
          onChanged();
        } else {
          owner_ = null;
          ownerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder getOwnerBuilder() {
        
        onChanged();
        return getOwnerFieldBuilder().getBuilder();
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getOwnerOrBuilder() {
        if (ownerBuilder_ != null) {
          return ownerBuilder_.getMessageOrBuilder();
        } else {
          return owner_ == null ?
              com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance() : owner_;
        }
      }
      /**
       * <code>.Identification owner = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> 
          getOwnerFieldBuilder() {
        if (ownerBuilder_ == null) {
          ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder>(
                  getOwner(),
                  getParentForChildren(),
                  isClean());
          owner_ = null;
        }
        return ownerBuilder_;
      }

      private java.lang.Object kind_ = "";
      /**
       * <pre>
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       * </pre>
       *
       * <code>string kind = 4;</code>
       * @return The kind.
       */
      public java.lang.String getKind() {
        java.lang.Object ref = kind_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kind_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       * </pre>
       *
       * <code>string kind = 4;</code>
       * @return The bytes for kind.
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        java.lang.Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       * </pre>
       *
       * <code>string kind = 4;</code>
       * @param value The kind to set.
       * @return This builder for chaining.
       */
      public Builder setKind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       * </pre>
       *
       * <code>string kind = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKind() {
        
        kind_ = getDefaultInstance().getKind();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       *protoc -I=/Users/ameya/T2R/src/main/resources/Models --java_out=/Users/ameya/T2R/src/main/java/ /Users/ameya/T2R/src/main/resources/Models/&#42;
       * </pre>
       *
       * <code>string kind = 4;</code>
       * @param value The bytes for kind to set.
       * @return This builder for chaining.
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kind_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Identification)
    }

    // @@protoc_insertion_point(class_scope:Identification)
    private static final com.t2r.common.models.ast.IdentificationOuterClass.Identification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.ast.IdentificationOuterClass.Identification();
    }

    public static com.t2r.common.models.ast.IdentificationOuterClass.Identification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Identification>
        PARSER = new com.google.protobuf.AbstractParser<Identification>() {
      @java.lang.Override
      public Identification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Identification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Identification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Identification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.t2r.common.models.ast.IdentificationOuterClass.Identification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Identification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Identification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Identification.proto\032\023TypeSignature.pr" +
      "oto\"j\n\016Identification\022\014\n\004name\030\001 \001(\t\022\034\n\004t" +
      "ype\030\002 \001(\0132\016.TypeSignature\022\036\n\005owner\030\003 \001(\013" +
      "2\017.Identification\022\014\n\004kind\030\004 \001(\tB\033\n\031com.t" +
      "2r.common.models.astb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.ast.TypeSignatureOuterClass.getDescriptor(),
        });
    internal_static_Identification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Identification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Identification_descriptor,
        new java.lang.String[] { "Name", "Type", "Owner", "Kind", });
    com.t2r.common.models.ast.TypeSignatureOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
