// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TFG.proto

package com.t2r.common.models.ast;

public final class TFGOuterClass {
  private TFGOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TFGOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TFG)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification> 
        getNodesList();
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    com.t2r.common.models.ast.IdentificationOuterClass.Identification getNodes(int index);
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    java.util.List<? extends com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getNodesOrBuilder(
        int index);

    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> 
        getEdgesList();
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getEdges(int index);
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    int getEdgesCount();
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    java.util.List<? extends com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder> 
        getEdgesOrBuilderList();
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder getEdgesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TFG}
   */
  public  static final class TFG extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TFG)
      TFGOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TFG.newBuilder() to construct.
    private TFG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TFG() {
      nodes_ = java.util.Collections.emptyList();
      edges_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TFG();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TFG(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodes_ = new java.util.ArrayList<com.t2r.common.models.ast.IdentificationOuterClass.Identification>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(
                  input.readMessage(com.t2r.common.models.ast.IdentificationOuterClass.Identification.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                edges_ = new java.util.ArrayList<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge>();
                mutable_bitField0_ |= 0x00000002;
              }
              edges_.add(
                  input.readMessage(com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          edges_ = java.util.Collections.unmodifiableList(edges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.ast.TFGOuterClass.TFG.class, com.t2r.common.models.ast.TFGOuterClass.TFG.Builder.class);
    }

    public interface EdgeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TFG.Edge)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 fst = 1;</code>
       * @return The fst.
       */
      int getFst();

      /**
       * <code>int32 snd = 2;</code>
       * @return The snd.
       */
      int getSnd();

      /**
       * <code>string edgeValue = 3;</code>
       * @return The edgeValue.
       */
      java.lang.String getEdgeValue();
      /**
       * <code>string edgeValue = 3;</code>
       * @return The bytes for edgeValue.
       */
      com.google.protobuf.ByteString
          getEdgeValueBytes();
    }
    /**
     * Protobuf type {@code TFG.Edge}
     */
    public  static final class Edge extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TFG.Edge)
        EdgeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Edge.newBuilder() to construct.
      private Edge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Edge() {
        edgeValue_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Edge();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Edge(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                fst_ = input.readInt32();
                break;
              }
              case 16: {

                snd_ = input.readInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                edgeValue_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_Edge_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.class, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder.class);
      }

      public static final int FST_FIELD_NUMBER = 1;
      private int fst_;
      /**
       * <code>int32 fst = 1;</code>
       * @return The fst.
       */
      public int getFst() {
        return fst_;
      }

      public static final int SND_FIELD_NUMBER = 2;
      private int snd_;
      /**
       * <code>int32 snd = 2;</code>
       * @return The snd.
       */
      public int getSnd() {
        return snd_;
      }

      public static final int EDGEVALUE_FIELD_NUMBER = 3;
      private volatile java.lang.Object edgeValue_;
      /**
       * <code>string edgeValue = 3;</code>
       * @return The edgeValue.
       */
      public java.lang.String getEdgeValue() {
        java.lang.Object ref = edgeValue_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          edgeValue_ = s;
          return s;
        }
      }
      /**
       * <code>string edgeValue = 3;</code>
       * @return The bytes for edgeValue.
       */
      public com.google.protobuf.ByteString
          getEdgeValueBytes() {
        java.lang.Object ref = edgeValue_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          edgeValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (fst_ != 0) {
          output.writeInt32(1, fst_);
        }
        if (snd_ != 0) {
          output.writeInt32(2, snd_);
        }
        if (!getEdgeValueBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, edgeValue_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (fst_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, fst_);
        }
        if (snd_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, snd_);
        }
        if (!getEdgeValueBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, edgeValue_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.t2r.common.models.ast.TFGOuterClass.TFG.Edge)) {
          return super.equals(obj);
        }
        com.t2r.common.models.ast.TFGOuterClass.TFG.Edge other = (com.t2r.common.models.ast.TFGOuterClass.TFG.Edge) obj;

        if (getFst()
            != other.getFst()) return false;
        if (getSnd()
            != other.getSnd()) return false;
        if (!getEdgeValue()
            .equals(other.getEdgeValue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FST_FIELD_NUMBER;
        hash = (53 * hash) + getFst();
        hash = (37 * hash) + SND_FIELD_NUMBER;
        hash = (53 * hash) + getSnd();
        hash = (37 * hash) + EDGEVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getEdgeValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.t2r.common.models.ast.TFGOuterClass.TFG.Edge prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TFG.Edge}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TFG.Edge)
          com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_Edge_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_Edge_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.class, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder.class);
        }

        // Construct using com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          fst_ = 0;

          snd_ = 0;

          edgeValue_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_Edge_descriptor;
        }

        @java.lang.Override
        public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getDefaultInstanceForType() {
          return com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.getDefaultInstance();
        }

        @java.lang.Override
        public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge build() {
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge buildPartial() {
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge result = new com.t2r.common.models.ast.TFGOuterClass.TFG.Edge(this);
          result.fst_ = fst_;
          result.snd_ = snd_;
          result.edgeValue_ = edgeValue_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.t2r.common.models.ast.TFGOuterClass.TFG.Edge) {
            return mergeFrom((com.t2r.common.models.ast.TFGOuterClass.TFG.Edge)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.t2r.common.models.ast.TFGOuterClass.TFG.Edge other) {
          if (other == com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.getDefaultInstance()) return this;
          if (other.getFst() != 0) {
            setFst(other.getFst());
          }
          if (other.getSnd() != 0) {
            setSnd(other.getSnd());
          }
          if (!other.getEdgeValue().isEmpty()) {
            edgeValue_ = other.edgeValue_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.t2r.common.models.ast.TFGOuterClass.TFG.Edge) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int fst_ ;
        /**
         * <code>int32 fst = 1;</code>
         * @return The fst.
         */
        public int getFst() {
          return fst_;
        }
        /**
         * <code>int32 fst = 1;</code>
         * @param value The fst to set.
         * @return This builder for chaining.
         */
        public Builder setFst(int value) {
          
          fst_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 fst = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFst() {
          
          fst_ = 0;
          onChanged();
          return this;
        }

        private int snd_ ;
        /**
         * <code>int32 snd = 2;</code>
         * @return The snd.
         */
        public int getSnd() {
          return snd_;
        }
        /**
         * <code>int32 snd = 2;</code>
         * @param value The snd to set.
         * @return This builder for chaining.
         */
        public Builder setSnd(int value) {
          
          snd_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 snd = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearSnd() {
          
          snd_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object edgeValue_ = "";
        /**
         * <code>string edgeValue = 3;</code>
         * @return The edgeValue.
         */
        public java.lang.String getEdgeValue() {
          java.lang.Object ref = edgeValue_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            edgeValue_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string edgeValue = 3;</code>
         * @return The bytes for edgeValue.
         */
        public com.google.protobuf.ByteString
            getEdgeValueBytes() {
          java.lang.Object ref = edgeValue_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            edgeValue_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string edgeValue = 3;</code>
         * @param value The edgeValue to set.
         * @return This builder for chaining.
         */
        public Builder setEdgeValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          edgeValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string edgeValue = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearEdgeValue() {
          
          edgeValue_ = getDefaultInstance().getEdgeValue();
          onChanged();
          return this;
        }
        /**
         * <code>string edgeValue = 3;</code>
         * @param value The bytes for edgeValue to set.
         * @return This builder for chaining.
         */
        public Builder setEdgeValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          edgeValue_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TFG.Edge)
      }

      // @@protoc_insertion_point(class_scope:TFG.Edge)
      private static final com.t2r.common.models.ast.TFGOuterClass.TFG.Edge DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.t2r.common.models.ast.TFGOuterClass.TFG.Edge();
      }

      public static com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Edge>
          PARSER = new com.google.protobuf.AbstractParser<Edge>() {
        @java.lang.Override
        public Edge parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Edge(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Edge> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Edge> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification> nodes_;
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    public java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    public java.util.List<? extends com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    public com.t2r.common.models.ast.IdentificationOuterClass.Identification getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .Identification nodes = 1;</code>
     */
    public com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    public static final int EDGES_FIELD_NUMBER = 2;
    private java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> edges_;
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    public java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> getEdgesList() {
      return edges_;
    }
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    public java.util.List<? extends com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder> 
        getEdgesOrBuilderList() {
      return edges_;
    }
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    public int getEdgesCount() {
      return edges_.size();
    }
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getEdges(int index) {
      return edges_.get(index);
    }
    /**
     * <code>repeated .TFG.Edge edges = 2;</code>
     */
    public com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder getEdgesOrBuilder(
        int index) {
      return edges_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      for (int i = 0; i < edges_.size(); i++) {
        output.writeMessage(2, edges_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      for (int i = 0; i < edges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, edges_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.ast.TFGOuterClass.TFG)) {
        return super.equals(obj);
      }
      com.t2r.common.models.ast.TFGOuterClass.TFG other = (com.t2r.common.models.ast.TFGOuterClass.TFG) obj;

      if (!getNodesList()
          .equals(other.getNodesList())) return false;
      if (!getEdgesList()
          .equals(other.getEdgesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      if (getEdgesCount() > 0) {
        hash = (37 * hash) + EDGES_FIELD_NUMBER;
        hash = (53 * hash) + getEdgesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.ast.TFGOuterClass.TFG parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.ast.TFGOuterClass.TFG prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TFG}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TFG)
        com.t2r.common.models.ast.TFGOuterClass.TFGOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.ast.TFGOuterClass.TFG.class, com.t2r.common.models.ast.TFGOuterClass.TFG.Builder.class);
      }

      // Construct using com.t2r.common.models.ast.TFGOuterClass.TFG.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
          getEdgesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.ast.TFGOuterClass.internal_static_TFG_descriptor;
      }

      @java.lang.Override
      public com.t2r.common.models.ast.TFGOuterClass.TFG getDefaultInstanceForType() {
        return com.t2r.common.models.ast.TFGOuterClass.TFG.getDefaultInstance();
      }

      @java.lang.Override
      public com.t2r.common.models.ast.TFGOuterClass.TFG build() {
        com.t2r.common.models.ast.TFGOuterClass.TFG result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.t2r.common.models.ast.TFGOuterClass.TFG buildPartial() {
        com.t2r.common.models.ast.TFGOuterClass.TFG result = new com.t2r.common.models.ast.TFGOuterClass.TFG(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        if (edgesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            edges_ = java.util.Collections.unmodifiableList(edges_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.edges_ = edges_;
        } else {
          result.edges_ = edgesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.ast.TFGOuterClass.TFG) {
          return mergeFrom((com.t2r.common.models.ast.TFGOuterClass.TFG)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.ast.TFGOuterClass.TFG other) {
        if (other == com.t2r.common.models.ast.TFGOuterClass.TFG.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        if (edgesBuilder_ == null) {
          if (!other.edges_.isEmpty()) {
            if (edges_.isEmpty()) {
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEdgesIsMutable();
              edges_.addAll(other.edges_);
            }
            onChanged();
          }
        } else {
          if (!other.edges_.isEmpty()) {
            if (edgesBuilder_.isEmpty()) {
              edgesBuilder_.dispose();
              edgesBuilder_ = null;
              edges_ = other.edges_;
              bitField0_ = (bitField0_ & ~0x00000002);
              edgesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEdgesFieldBuilder() : null;
            } else {
              edgesBuilder_.addAllMessages(other.edges_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.ast.TFGOuterClass.TFG parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.ast.TFGOuterClass.TFG) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodes_ = new java.util.ArrayList<com.t2r.common.models.ast.IdentificationOuterClass.Identification>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.t2r.common.models.ast.IdentificationOuterClass.Identification value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder setNodes(
          int index, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder addNodes(com.t2r.common.models.ast.IdentificationOuterClass.Identification value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.t2r.common.models.ast.IdentificationOuterClass.Identification value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder addNodes(
          com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder addNodes(
          int index, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.t2r.common.models.ast.IdentificationOuterClass.Identification> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public java.util.List<? extends com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance());
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.t2r.common.models.ast.IdentificationOuterClass.Identification.getDefaultInstance());
      }
      /**
       * <code>repeated .Identification nodes = 1;</code>
       */
      public java.util.List<com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.t2r.common.models.ast.IdentificationOuterClass.Identification, com.t2r.common.models.ast.IdentificationOuterClass.Identification.Builder, com.t2r.common.models.ast.IdentificationOuterClass.IdentificationOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      private java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> edges_ =
        java.util.Collections.emptyList();
      private void ensureEdgesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          edges_ = new java.util.ArrayList<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge>(edges_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder, com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder> edgesBuilder_;

      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> getEdgesList() {
        if (edgesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(edges_);
        } else {
          return edgesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public int getEdgesCount() {
        if (edgesBuilder_ == null) {
          return edges_.size();
        } else {
          return edgesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge getEdges(int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);
        } else {
          return edgesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder setEdges(
          int index, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.set(index, value);
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder setEdges(
          int index, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.set(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder addEdges(com.t2r.common.models.ast.TFGOuterClass.TFG.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder addEdges(
          int index, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge value) {
        if (edgesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEdgesIsMutable();
          edges_.add(index, value);
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder addEdges(
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder addEdges(
          int index, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder builderForValue) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.add(index, builderForValue.build());
          onChanged();
        } else {
          edgesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder addAllEdges(
          java.lang.Iterable<? extends com.t2r.common.models.ast.TFGOuterClass.TFG.Edge> values) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, edges_);
          onChanged();
        } else {
          edgesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder clearEdges() {
        if (edgesBuilder_ == null) {
          edges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          edgesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public Builder removeEdges(int index) {
        if (edgesBuilder_ == null) {
          ensureEdgesIsMutable();
          edges_.remove(index);
          onChanged();
        } else {
          edgesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder getEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder getEdgesOrBuilder(
          int index) {
        if (edgesBuilder_ == null) {
          return edges_.get(index);  } else {
          return edgesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public java.util.List<? extends com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder> 
           getEdgesOrBuilderList() {
        if (edgesBuilder_ != null) {
          return edgesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(edges_);
        }
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder addEdgesBuilder() {
        return getEdgesFieldBuilder().addBuilder(
            com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder addEdgesBuilder(
          int index) {
        return getEdgesFieldBuilder().addBuilder(
            index, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.getDefaultInstance());
      }
      /**
       * <code>repeated .TFG.Edge edges = 2;</code>
       */
      public java.util.List<com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder> 
           getEdgesBuilderList() {
        return getEdgesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.ast.TFGOuterClass.TFG.Edge, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder, com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder> 
          getEdgesFieldBuilder() {
        if (edgesBuilder_ == null) {
          edgesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.t2r.common.models.ast.TFGOuterClass.TFG.Edge, com.t2r.common.models.ast.TFGOuterClass.TFG.Edge.Builder, com.t2r.common.models.ast.TFGOuterClass.TFG.EdgeOrBuilder>(
                  edges_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          edges_ = null;
        }
        return edgesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TFG)
    }

    // @@protoc_insertion_point(class_scope:TFG)
    private static final com.t2r.common.models.ast.TFGOuterClass.TFG DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.ast.TFGOuterClass.TFG();
    }

    public static com.t2r.common.models.ast.TFGOuterClass.TFG getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TFG>
        PARSER = new com.google.protobuf.AbstractParser<TFG>() {
      @java.lang.Override
      public TFG parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TFG(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TFG> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TFG> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.t2r.common.models.ast.TFGOuterClass.TFG getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TFG_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TFG_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TFG_Edge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TFG_Edge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tTFG.proto\032\024Identification.proto\"t\n\003TFG" +
      "\022\036\n\005nodes\030\001 \003(\0132\017.Identification\022\030\n\005edge" +
      "s\030\002 \003(\0132\t.TFG.Edge\0323\n\004Edge\022\013\n\003fst\030\001 \001(\005\022" +
      "\013\n\003snd\030\002 \001(\005\022\021\n\tedgeValue\030\003 \001(\tB\033\n\031com.t" +
      "2r.common.models.astb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.ast.IdentificationOuterClass.getDescriptor(),
        });
    internal_static_TFG_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TFG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TFG_descriptor,
        new java.lang.String[] { "Nodes", "Edges", });
    internal_static_TFG_Edge_descriptor =
      internal_static_TFG_descriptor.getNestedTypes().get(0);
    internal_static_TFG_Edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TFG_Edge_descriptor,
        new java.lang.String[] { "Fst", "Snd", "EdgeValue", });
    com.t2r.common.models.ast.IdentificationOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
