// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MigrationData.proto

public final class MigrationDataOuterClass {
  private MigrationDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MigrationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MigrationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TypeGraph type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>.TypeGraph type = 1;</code>
     * @return The type.
     */
    com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getType();
    /**
     * <code>.TypeGraph type = 1;</code>
     */
    com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getTypeOrBuilder();

    /**
     * <code>double ratio = 2;</code>
     * @return The ratio.
     */
    double getRatio();

    /**
     * <code>.NameSpace namespace = 3;</code>
     * @return The enum numeric value on the wire for namespace.
     */
    int getNamespaceValue();
    /**
     * <code>.NameSpace namespace = 3;</code>
     * @return The namespace.
     */
    com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace getNamespace();

    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    java.util.List<MigrationDataOuterClass.MigrationData.CommitToType> 
        getCommitToTypeList();
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    MigrationDataOuterClass.MigrationData.CommitToType getCommitToType(int index);
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    int getCommitToTypeCount();
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    java.util.List<? extends MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder> 
        getCommitToTypeOrBuilderList();
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder getCommitToTypeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MigrationData}
   */
  public  static final class MigrationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MigrationData)
      MigrationDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MigrationData.newBuilder() to construct.
    private MigrationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MigrationData() {
      namespace_ = 0;
      commitToType_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MigrationData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MigrationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder subBuilder = null;
              if (type_ != null) {
                subBuilder = type_.toBuilder();
              }
              type_ = input.readMessage(com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(type_);
                type_ = subBuilder.buildPartial();
              }

              break;
            }
            case 17: {

              ratio_ = input.readDouble();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              namespace_ = rawValue;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                commitToType_ = new java.util.ArrayList<MigrationDataOuterClass.MigrationData.CommitToType>();
                mutable_bitField0_ |= 0x00000001;
              }
              commitToType_.add(
                  input.readMessage(MigrationDataOuterClass.MigrationData.CommitToType.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          commitToType_ = java.util.Collections.unmodifiableList(commitToType_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MigrationDataOuterClass.internal_static_MigrationData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MigrationDataOuterClass.internal_static_MigrationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MigrationDataOuterClass.MigrationData.class, MigrationDataOuterClass.MigrationData.Builder.class);
    }

    public interface CommitToTypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MigrationData.CommitToType)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string sha = 2;</code>
       * @return The sha.
       */
      java.lang.String getSha();
      /**
       * <code>string sha = 2;</code>
       * @return The bytes for sha.
       */
      com.google.protobuf.ByteString
          getShaBytes();

      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> 
          getToTypeList();
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getToType(int index);
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      int getToTypeCount();
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      java.util.List<? extends com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> 
          getToTypeOrBuilderList();
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getToTypeOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code MigrationData.CommitToType}
     */
    public  static final class CommitToType extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MigrationData.CommitToType)
        CommitToTypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CommitToType.newBuilder() to construct.
      private CommitToType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CommitToType() {
        sha_ = "";
        toType_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new CommitToType();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CommitToType(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  toType_ = new java.util.ArrayList<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph>();
                  mutable_bitField0_ |= 0x00000001;
                }
                toType_.add(
                    input.readMessage(com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.parser(), extensionRegistry));
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                sha_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            toType_ = java.util.Collections.unmodifiableList(toType_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MigrationDataOuterClass.internal_static_MigrationData_CommitToType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MigrationDataOuterClass.internal_static_MigrationData_CommitToType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MigrationDataOuterClass.MigrationData.CommitToType.class, MigrationDataOuterClass.MigrationData.CommitToType.Builder.class);
      }

      public static final int SHA_FIELD_NUMBER = 2;
      private volatile java.lang.Object sha_;
      /**
       * <code>string sha = 2;</code>
       * @return The sha.
       */
      public java.lang.String getSha() {
        java.lang.Object ref = sha_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sha_ = s;
          return s;
        }
      }
      /**
       * <code>string sha = 2;</code>
       * @return The bytes for sha.
       */
      public com.google.protobuf.ByteString
          getShaBytes() {
        java.lang.Object ref = sha_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TOTYPE_FIELD_NUMBER = 1;
      private java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> toType_;
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      public java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> getToTypeList() {
        return toType_;
      }
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      public java.util.List<? extends com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> 
          getToTypeOrBuilderList() {
        return toType_;
      }
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      public int getToTypeCount() {
        return toType_.size();
      }
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getToType(int index) {
        return toType_.get(index);
      }
      /**
       * <code>repeated .TypeGraph toType = 1;</code>
       */
      public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getToTypeOrBuilder(
          int index) {
        return toType_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < toType_.size(); i++) {
          output.writeMessage(1, toType_.get(i));
        }
        if (!getShaBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sha_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < toType_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, toType_.get(i));
        }
        if (!getShaBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sha_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MigrationDataOuterClass.MigrationData.CommitToType)) {
          return super.equals(obj);
        }
        MigrationDataOuterClass.MigrationData.CommitToType other = (MigrationDataOuterClass.MigrationData.CommitToType) obj;

        if (!getSha()
            .equals(other.getSha())) return false;
        if (!getToTypeList()
            .equals(other.getToTypeList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SHA_FIELD_NUMBER;
        hash = (53 * hash) + getSha().hashCode();
        if (getToTypeCount() > 0) {
          hash = (37 * hash) + TOTYPE_FIELD_NUMBER;
          hash = (53 * hash) + getToTypeList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MigrationDataOuterClass.MigrationData.CommitToType parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MigrationDataOuterClass.MigrationData.CommitToType prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MigrationData.CommitToType}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MigrationData.CommitToType)
          MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MigrationDataOuterClass.internal_static_MigrationData_CommitToType_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MigrationDataOuterClass.internal_static_MigrationData_CommitToType_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MigrationDataOuterClass.MigrationData.CommitToType.class, MigrationDataOuterClass.MigrationData.CommitToType.Builder.class);
        }

        // Construct using MigrationDataOuterClass.MigrationData.CommitToType.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getToTypeFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          sha_ = "";

          if (toTypeBuilder_ == null) {
            toType_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            toTypeBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MigrationDataOuterClass.internal_static_MigrationData_CommitToType_descriptor;
        }

        @java.lang.Override
        public MigrationDataOuterClass.MigrationData.CommitToType getDefaultInstanceForType() {
          return MigrationDataOuterClass.MigrationData.CommitToType.getDefaultInstance();
        }

        @java.lang.Override
        public MigrationDataOuterClass.MigrationData.CommitToType build() {
          MigrationDataOuterClass.MigrationData.CommitToType result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public MigrationDataOuterClass.MigrationData.CommitToType buildPartial() {
          MigrationDataOuterClass.MigrationData.CommitToType result = new MigrationDataOuterClass.MigrationData.CommitToType(this);
          int from_bitField0_ = bitField0_;
          result.sha_ = sha_;
          if (toTypeBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              toType_ = java.util.Collections.unmodifiableList(toType_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.toType_ = toType_;
          } else {
            result.toType_ = toTypeBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MigrationDataOuterClass.MigrationData.CommitToType) {
            return mergeFrom((MigrationDataOuterClass.MigrationData.CommitToType)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MigrationDataOuterClass.MigrationData.CommitToType other) {
          if (other == MigrationDataOuterClass.MigrationData.CommitToType.getDefaultInstance()) return this;
          if (!other.getSha().isEmpty()) {
            sha_ = other.sha_;
            onChanged();
          }
          if (toTypeBuilder_ == null) {
            if (!other.toType_.isEmpty()) {
              if (toType_.isEmpty()) {
                toType_ = other.toType_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureToTypeIsMutable();
                toType_.addAll(other.toType_);
              }
              onChanged();
            }
          } else {
            if (!other.toType_.isEmpty()) {
              if (toTypeBuilder_.isEmpty()) {
                toTypeBuilder_.dispose();
                toTypeBuilder_ = null;
                toType_ = other.toType_;
                bitField0_ = (bitField0_ & ~0x00000001);
                toTypeBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getToTypeFieldBuilder() : null;
              } else {
                toTypeBuilder_.addAllMessages(other.toType_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MigrationDataOuterClass.MigrationData.CommitToType parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MigrationDataOuterClass.MigrationData.CommitToType) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object sha_ = "";
        /**
         * <code>string sha = 2;</code>
         * @return The sha.
         */
        public java.lang.String getSha() {
          java.lang.Object ref = sha_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sha_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string sha = 2;</code>
         * @return The bytes for sha.
         */
        public com.google.protobuf.ByteString
            getShaBytes() {
          java.lang.Object ref = sha_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sha_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string sha = 2;</code>
         * @param value The sha to set.
         * @return This builder for chaining.
         */
        public Builder setSha(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          sha_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string sha = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearSha() {
          
          sha_ = getDefaultInstance().getSha();
          onChanged();
          return this;
        }
        /**
         * <code>string sha = 2;</code>
         * @param value The bytes for sha to set.
         * @return This builder for chaining.
         */
        public Builder setShaBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          sha_ = value;
          onChanged();
          return this;
        }

        private java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> toType_ =
          java.util.Collections.emptyList();
        private void ensureToTypeIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            toType_ = new java.util.ArrayList<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph>(toType_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> toTypeBuilder_;

        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> getToTypeList() {
          if (toTypeBuilder_ == null) {
            return java.util.Collections.unmodifiableList(toType_);
          } else {
            return toTypeBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public int getToTypeCount() {
          if (toTypeBuilder_ == null) {
            return toType_.size();
          } else {
            return toTypeBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getToType(int index) {
          if (toTypeBuilder_ == null) {
            return toType_.get(index);
          } else {
            return toTypeBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder setToType(
            int index, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph value) {
          if (toTypeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureToTypeIsMutable();
            toType_.set(index, value);
            onChanged();
          } else {
            toTypeBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder setToType(
            int index, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder builderForValue) {
          if (toTypeBuilder_ == null) {
            ensureToTypeIsMutable();
            toType_.set(index, builderForValue.build());
            onChanged();
          } else {
            toTypeBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder addToType(com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph value) {
          if (toTypeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureToTypeIsMutable();
            toType_.add(value);
            onChanged();
          } else {
            toTypeBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder addToType(
            int index, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph value) {
          if (toTypeBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureToTypeIsMutable();
            toType_.add(index, value);
            onChanged();
          } else {
            toTypeBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder addToType(
            com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder builderForValue) {
          if (toTypeBuilder_ == null) {
            ensureToTypeIsMutable();
            toType_.add(builderForValue.build());
            onChanged();
          } else {
            toTypeBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder addToType(
            int index, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder builderForValue) {
          if (toTypeBuilder_ == null) {
            ensureToTypeIsMutable();
            toType_.add(index, builderForValue.build());
            onChanged();
          } else {
            toTypeBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder addAllToType(
            java.lang.Iterable<? extends com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph> values) {
          if (toTypeBuilder_ == null) {
            ensureToTypeIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, toType_);
            onChanged();
          } else {
            toTypeBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder clearToType() {
          if (toTypeBuilder_ == null) {
            toType_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            toTypeBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public Builder removeToType(int index) {
          if (toTypeBuilder_ == null) {
            ensureToTypeIsMutable();
            toType_.remove(index);
            onChanged();
          } else {
            toTypeBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder getToTypeBuilder(
            int index) {
          return getToTypeFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getToTypeOrBuilder(
            int index) {
          if (toTypeBuilder_ == null) {
            return toType_.get(index);  } else {
            return toTypeBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public java.util.List<? extends com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> 
             getToTypeOrBuilderList() {
          if (toTypeBuilder_ != null) {
            return toTypeBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(toType_);
          }
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder addToTypeBuilder() {
          return getToTypeFieldBuilder().addBuilder(
              com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.getDefaultInstance());
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder addToTypeBuilder(
            int index) {
          return getToTypeFieldBuilder().addBuilder(
              index, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.getDefaultInstance());
        }
        /**
         * <code>repeated .TypeGraph toType = 1;</code>
         */
        public java.util.List<com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder> 
             getToTypeBuilderList() {
          return getToTypeFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> 
            getToTypeFieldBuilder() {
          if (toTypeBuilder_ == null) {
            toTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder>(
                    toType_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            toType_ = null;
          }
          return toTypeBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MigrationData.CommitToType)
      }

      // @@protoc_insertion_point(class_scope:MigrationData.CommitToType)
      private static final MigrationDataOuterClass.MigrationData.CommitToType DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MigrationDataOuterClass.MigrationData.CommitToType();
      }

      public static MigrationDataOuterClass.MigrationData.CommitToType getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CommitToType>
          PARSER = new com.google.protobuf.AbstractParser<CommitToType>() {
        @java.lang.Override
        public CommitToType parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommitToType(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CommitToType> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CommitToType> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public MigrationDataOuterClass.MigrationData.CommitToType getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph type_;
    /**
     * <code>.TypeGraph type = 1;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return type_ != null;
    }
    /**
     * <code>.TypeGraph type = 1;</code>
     * @return The type.
     */
    public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getType() {
      return type_ == null ? com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.getDefaultInstance() : type_;
    }
    /**
     * <code>.TypeGraph type = 1;</code>
     */
    public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getTypeOrBuilder() {
      return getType();
    }

    public static final int RATIO_FIELD_NUMBER = 2;
    private double ratio_;
    /**
     * <code>double ratio = 2;</code>
     * @return The ratio.
     */
    public double getRatio() {
      return ratio_;
    }

    public static final int NAMESPACE_FIELD_NUMBER = 3;
    private int namespace_;
    /**
     * <code>.NameSpace namespace = 3;</code>
     * @return The enum numeric value on the wire for namespace.
     */
    public int getNamespaceValue() {
      return namespace_;
    }
    /**
     * <code>.NameSpace namespace = 3;</code>
     * @return The namespace.
     */
    public com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace getNamespace() {
      @SuppressWarnings("deprecation")
      com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace result = com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.valueOf(namespace_);
      return result == null ? com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.UNRECOGNIZED : result;
    }

    public static final int COMMITTOTYPE_FIELD_NUMBER = 4;
    private java.util.List<MigrationDataOuterClass.MigrationData.CommitToType> commitToType_;
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    public java.util.List<MigrationDataOuterClass.MigrationData.CommitToType> getCommitToTypeList() {
      return commitToType_;
    }
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    public java.util.List<? extends MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder> 
        getCommitToTypeOrBuilderList() {
      return commitToType_;
    }
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    public int getCommitToTypeCount() {
      return commitToType_.size();
    }
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    public MigrationDataOuterClass.MigrationData.CommitToType getCommitToType(int index) {
      return commitToType_.get(index);
    }
    /**
     * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
     */
    public MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder getCommitToTypeOrBuilder(
        int index) {
      return commitToType_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != null) {
        output.writeMessage(1, getType());
      }
      if (ratio_ != 0D) {
        output.writeDouble(2, ratio_);
      }
      if (namespace_ != com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.TypeVariable.getNumber()) {
        output.writeEnum(3, namespace_);
      }
      for (int i = 0; i < commitToType_.size(); i++) {
        output.writeMessage(4, commitToType_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getType());
      }
      if (ratio_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, ratio_);
      }
      if (namespace_ != com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.TypeVariable.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, namespace_);
      }
      for (int i = 0; i < commitToType_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, commitToType_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MigrationDataOuterClass.MigrationData)) {
        return super.equals(obj);
      }
      MigrationDataOuterClass.MigrationData other = (MigrationDataOuterClass.MigrationData) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getRatio())
          != java.lang.Double.doubleToLongBits(
              other.getRatio())) return false;
      if (namespace_ != other.namespace_) return false;
      if (!getCommitToTypeList()
          .equals(other.getCommitToTypeList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (37 * hash) + RATIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRatio()));
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + namespace_;
      if (getCommitToTypeCount() > 0) {
        hash = (37 * hash) + COMMITTOTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCommitToTypeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MigrationDataOuterClass.MigrationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MigrationDataOuterClass.MigrationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MigrationDataOuterClass.MigrationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MigrationDataOuterClass.MigrationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MigrationDataOuterClass.MigrationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MigrationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MigrationData)
        MigrationDataOuterClass.MigrationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MigrationDataOuterClass.internal_static_MigrationData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MigrationDataOuterClass.internal_static_MigrationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MigrationDataOuterClass.MigrationData.class, MigrationDataOuterClass.MigrationData.Builder.class);
      }

      // Construct using MigrationDataOuterClass.MigrationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommitToTypeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (typeBuilder_ == null) {
          type_ = null;
        } else {
          type_ = null;
          typeBuilder_ = null;
        }
        ratio_ = 0D;

        namespace_ = 0;

        if (commitToTypeBuilder_ == null) {
          commitToType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commitToTypeBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MigrationDataOuterClass.internal_static_MigrationData_descriptor;
      }

      @java.lang.Override
      public MigrationDataOuterClass.MigrationData getDefaultInstanceForType() {
        return MigrationDataOuterClass.MigrationData.getDefaultInstance();
      }

      @java.lang.Override
      public MigrationDataOuterClass.MigrationData build() {
        MigrationDataOuterClass.MigrationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MigrationDataOuterClass.MigrationData buildPartial() {
        MigrationDataOuterClass.MigrationData result = new MigrationDataOuterClass.MigrationData(this);
        int from_bitField0_ = bitField0_;
        if (typeBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        result.ratio_ = ratio_;
        result.namespace_ = namespace_;
        if (commitToTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            commitToType_ = java.util.Collections.unmodifiableList(commitToType_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.commitToType_ = commitToType_;
        } else {
          result.commitToType_ = commitToTypeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MigrationDataOuterClass.MigrationData) {
          return mergeFrom((MigrationDataOuterClass.MigrationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MigrationDataOuterClass.MigrationData other) {
        if (other == MigrationDataOuterClass.MigrationData.getDefaultInstance()) return this;
        if (other.hasType()) {
          mergeType(other.getType());
        }
        if (other.getRatio() != 0D) {
          setRatio(other.getRatio());
        }
        if (other.namespace_ != 0) {
          setNamespaceValue(other.getNamespaceValue());
        }
        if (commitToTypeBuilder_ == null) {
          if (!other.commitToType_.isEmpty()) {
            if (commitToType_.isEmpty()) {
              commitToType_ = other.commitToType_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommitToTypeIsMutable();
              commitToType_.addAll(other.commitToType_);
            }
            onChanged();
          }
        } else {
          if (!other.commitToType_.isEmpty()) {
            if (commitToTypeBuilder_.isEmpty()) {
              commitToTypeBuilder_.dispose();
              commitToTypeBuilder_ = null;
              commitToType_ = other.commitToType_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commitToTypeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCommitToTypeFieldBuilder() : null;
            } else {
              commitToTypeBuilder_.addAllMessages(other.commitToType_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MigrationDataOuterClass.MigrationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MigrationDataOuterClass.MigrationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph type_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> typeBuilder_;
      /**
       * <code>.TypeGraph type = 1;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return typeBuilder_ != null || type_ != null;
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       * @return The type.
       */
      public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph getType() {
        if (typeBuilder_ == null) {
          return type_ == null ? com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.getDefaultInstance() : type_;
        } else {
          return typeBuilder_.getMessage();
        }
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public Builder setType(com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public Builder setType(
          com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder builderForValue) {
        if (typeBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public Builder mergeType(com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph value) {
        if (typeBuilder_ == null) {
          if (type_ != null) {
            type_ =
              com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.newBuilder(type_).mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          typeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = null;
          onChanged();
        } else {
          type_ = null;
          typeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder getTypeBuilder() {
        
        onChanged();
        return getTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      public com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder getTypeOrBuilder() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilder();
        } else {
          return type_ == null ?
              com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.getDefaultInstance() : type_;
        }
      }
      /**
       * <code>.TypeGraph type = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraph.Builder, com.t2r.common.models.ast.TypeGraphOuterClass.TypeGraphOrBuilder>(
                  getType(),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }

      private double ratio_ ;
      /**
       * <code>double ratio = 2;</code>
       * @return The ratio.
       */
      public double getRatio() {
        return ratio_;
      }
      /**
       * <code>double ratio = 2;</code>
       * @param value The ratio to set.
       * @return This builder for chaining.
       */
      public Builder setRatio(double value) {
        
        ratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double ratio = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRatio() {
        
        ratio_ = 0D;
        onChanged();
        return this;
      }

      private int namespace_ = 0;
      /**
       * <code>.NameSpace namespace = 3;</code>
       * @return The enum numeric value on the wire for namespace.
       */
      public int getNamespaceValue() {
        return namespace_;
      }
      /**
       * <code>.NameSpace namespace = 3;</code>
       * @param value The enum numeric value on the wire for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceValue(int value) {
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.NameSpace namespace = 3;</code>
       * @return The namespace.
       */
      public com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace getNamespace() {
        @SuppressWarnings("deprecation")
        com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace result = com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.valueOf(namespace_);
        return result == null ? com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace.UNRECOGNIZED : result;
      }
      /**
       * <code>.NameSpace namespace = 3;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(com.t2r.common.models.refactorings.NameSpaceOuterClass.NameSpace value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        namespace_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.NameSpace namespace = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<MigrationDataOuterClass.MigrationData.CommitToType> commitToType_ =
        java.util.Collections.emptyList();
      private void ensureCommitToTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          commitToType_ = new java.util.ArrayList<MigrationDataOuterClass.MigrationData.CommitToType>(commitToType_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MigrationDataOuterClass.MigrationData.CommitToType, MigrationDataOuterClass.MigrationData.CommitToType.Builder, MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder> commitToTypeBuilder_;

      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public java.util.List<MigrationDataOuterClass.MigrationData.CommitToType> getCommitToTypeList() {
        if (commitToTypeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(commitToType_);
        } else {
          return commitToTypeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public int getCommitToTypeCount() {
        if (commitToTypeBuilder_ == null) {
          return commitToType_.size();
        } else {
          return commitToTypeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public MigrationDataOuterClass.MigrationData.CommitToType getCommitToType(int index) {
        if (commitToTypeBuilder_ == null) {
          return commitToType_.get(index);
        } else {
          return commitToTypeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder setCommitToType(
          int index, MigrationDataOuterClass.MigrationData.CommitToType value) {
        if (commitToTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommitToTypeIsMutable();
          commitToType_.set(index, value);
          onChanged();
        } else {
          commitToTypeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder setCommitToType(
          int index, MigrationDataOuterClass.MigrationData.CommitToType.Builder builderForValue) {
        if (commitToTypeBuilder_ == null) {
          ensureCommitToTypeIsMutable();
          commitToType_.set(index, builderForValue.build());
          onChanged();
        } else {
          commitToTypeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder addCommitToType(MigrationDataOuterClass.MigrationData.CommitToType value) {
        if (commitToTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommitToTypeIsMutable();
          commitToType_.add(value);
          onChanged();
        } else {
          commitToTypeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder addCommitToType(
          int index, MigrationDataOuterClass.MigrationData.CommitToType value) {
        if (commitToTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommitToTypeIsMutable();
          commitToType_.add(index, value);
          onChanged();
        } else {
          commitToTypeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder addCommitToType(
          MigrationDataOuterClass.MigrationData.CommitToType.Builder builderForValue) {
        if (commitToTypeBuilder_ == null) {
          ensureCommitToTypeIsMutable();
          commitToType_.add(builderForValue.build());
          onChanged();
        } else {
          commitToTypeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder addCommitToType(
          int index, MigrationDataOuterClass.MigrationData.CommitToType.Builder builderForValue) {
        if (commitToTypeBuilder_ == null) {
          ensureCommitToTypeIsMutable();
          commitToType_.add(index, builderForValue.build());
          onChanged();
        } else {
          commitToTypeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder addAllCommitToType(
          java.lang.Iterable<? extends MigrationDataOuterClass.MigrationData.CommitToType> values) {
        if (commitToTypeBuilder_ == null) {
          ensureCommitToTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, commitToType_);
          onChanged();
        } else {
          commitToTypeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder clearCommitToType() {
        if (commitToTypeBuilder_ == null) {
          commitToType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commitToTypeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public Builder removeCommitToType(int index) {
        if (commitToTypeBuilder_ == null) {
          ensureCommitToTypeIsMutable();
          commitToType_.remove(index);
          onChanged();
        } else {
          commitToTypeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public MigrationDataOuterClass.MigrationData.CommitToType.Builder getCommitToTypeBuilder(
          int index) {
        return getCommitToTypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder getCommitToTypeOrBuilder(
          int index) {
        if (commitToTypeBuilder_ == null) {
          return commitToType_.get(index);  } else {
          return commitToTypeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public java.util.List<? extends MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder> 
           getCommitToTypeOrBuilderList() {
        if (commitToTypeBuilder_ != null) {
          return commitToTypeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(commitToType_);
        }
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public MigrationDataOuterClass.MigrationData.CommitToType.Builder addCommitToTypeBuilder() {
        return getCommitToTypeFieldBuilder().addBuilder(
            MigrationDataOuterClass.MigrationData.CommitToType.getDefaultInstance());
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public MigrationDataOuterClass.MigrationData.CommitToType.Builder addCommitToTypeBuilder(
          int index) {
        return getCommitToTypeFieldBuilder().addBuilder(
            index, MigrationDataOuterClass.MigrationData.CommitToType.getDefaultInstance());
      }
      /**
       * <code>repeated .MigrationData.CommitToType commitToType = 4;</code>
       */
      public java.util.List<MigrationDataOuterClass.MigrationData.CommitToType.Builder> 
           getCommitToTypeBuilderList() {
        return getCommitToTypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MigrationDataOuterClass.MigrationData.CommitToType, MigrationDataOuterClass.MigrationData.CommitToType.Builder, MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder> 
          getCommitToTypeFieldBuilder() {
        if (commitToTypeBuilder_ == null) {
          commitToTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MigrationDataOuterClass.MigrationData.CommitToType, MigrationDataOuterClass.MigrationData.CommitToType.Builder, MigrationDataOuterClass.MigrationData.CommitToTypeOrBuilder>(
                  commitToType_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          commitToType_ = null;
        }
        return commitToTypeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MigrationData)
    }

    // @@protoc_insertion_point(class_scope:MigrationData)
    private static final MigrationDataOuterClass.MigrationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MigrationDataOuterClass.MigrationData();
    }

    public static MigrationDataOuterClass.MigrationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MigrationData>
        PARSER = new com.google.protobuf.AbstractParser<MigrationData>() {
      @java.lang.Override
      public MigrationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MigrationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MigrationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MigrationData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MigrationDataOuterClass.MigrationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MigrationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MigrationData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MigrationData_CommitToType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MigrationData_CommitToType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MigrationData.proto\032\017TypeGraph.proto\032\017" +
      "NameSpace.proto\"\303\001\n\rMigrationData\022\030\n\004typ" +
      "e\030\001 \001(\0132\n.TypeGraph\022\r\n\005ratio\030\002 \001(\001\022\035\n\tna" +
      "mespace\030\003 \001(\0162\n.NameSpace\0221\n\014commitToTyp" +
      "e\030\004 \003(\0132\033.MigrationData.CommitToType\0327\n\014" +
      "CommitToType\022\013\n\003sha\030\002 \001(\t\022\032\n\006toType\030\001 \003(" +
      "\0132\n.TypeGraphb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.ast.TypeGraphOuterClass.getDescriptor(),
          com.t2r.common.models.refactorings.NameSpaceOuterClass.getDescriptor(),
        });
    internal_static_MigrationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MigrationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MigrationData_descriptor,
        new java.lang.String[] { "Type", "Ratio", "Namespace", "CommitToType", });
    internal_static_MigrationData_CommitToType_descriptor =
      internal_static_MigrationData_descriptor.getNestedTypes().get(0);
    internal_static_MigrationData_CommitToType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MigrationData_CommitToType_descriptor,
        new java.lang.String[] { "Sha", "ToType", });
    com.t2r.common.models.ast.TypeGraphOuterClass.getDescriptor();
    com.t2r.common.models.refactorings.NameSpaceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
