// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElementKind.proto

package com.t2r.common.models.refactorings;

public final class ElementKindOuterClass {
  private ElementKindOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ElementKind}
   */
  public enum ElementKind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Field = 0;</code>
     */
    Field(0),
    /**
     * <code>LocalVariable = 2;</code>
     */
    LocalVariable(2),
    /**
     * <code>Parameter = 3;</code>
     */
    Parameter(3),
    /**
     * <code>Return = 4;</code>
     */
    Return(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Field = 0;</code>
     */
    public static final int Field_VALUE = 0;
    /**
     * <code>LocalVariable = 2;</code>
     */
    public static final int LocalVariable_VALUE = 2;
    /**
     * <code>Parameter = 3;</code>
     */
    public static final int Parameter_VALUE = 3;
    /**
     * <code>Return = 4;</code>
     */
    public static final int Return_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ElementKind valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ElementKind forNumber(int value) {
      switch (value) {
        case 0: return Field;
        case 2: return LocalVariable;
        case 3: return Parameter;
        case 4: return Return;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ElementKind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ElementKind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ElementKind>() {
            public ElementKind findValueByNumber(int number) {
              return ElementKind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.t2r.common.models.refactorings.ElementKindOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ElementKind[] VALUES = values();

    public static ElementKind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ElementKind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ElementKind)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ElementKind.proto*F\n\013ElementKind\022\t\n\005Fi" +
      "eld\020\000\022\021\n\rLocalVariable\020\002\022\r\n\tParameter\020\003\022" +
      "\n\n\006Return\020\004B$\n\"com.t2r.common.models.ref" +
      "actoringsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
