// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TheWorld.proto

package com.t2r.common.models.refactorings;

public final class TheWorldOuterClass {
  private TheWorldOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TheWorldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TheWorld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sha = 5;</code>
     * @return The sha.
     */
    java.lang.String getSha();
    /**
     * <code>string sha = 5;</code>
     * @return The bytes for sha.
     */
    com.google.protobuf.ByteString
        getShaBytes();

    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */
    int getVisibilityMapCount();
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */
    boolean containsVisibilityMap(
        java.lang.String key);
    /**
     * Use {@link #getVisibilityMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getVisibilityMap();
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getVisibilityMapMap();
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    int getVisibilityMapOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    int getVisibilityMapOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */
    int getTypeKindMapCount();
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */
    boolean containsTypeKindMap(
        java.lang.String key);
    /**
     * Use {@link #getTypeKindMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getTypeKindMap();
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getTypeKindMapMap();
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    int getTypeKindMapOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    int getTypeKindMapOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */
    int getNameSpaceMapCount();
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */
    boolean containsNameSpaceMap(
        java.lang.String key);
    /**
     * Use {@link #getNameSpaceMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getNameSpaceMap();
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getNameSpaceMapMap();
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    int getNameSpaceMapOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    int getNameSpaceMapOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */
    int getElementKindMapCount();
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */
    boolean containsElementKindMap(
        java.lang.String key);
    /**
     * Use {@link #getElementKindMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getElementKindMap();
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getElementKindMapMap();
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    int getElementKindMapOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    int getElementKindMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code TheWorld}
   */
  public  static final class TheWorld extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TheWorld)
      TheWorldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TheWorld.newBuilder() to construct.
    private TheWorld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TheWorld() {
      sha_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TheWorld();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TheWorld(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                visibilityMap_ = com.google.protobuf.MapField.newMapField(
                    VisibilityMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              visibilityMap__ = input.readMessage(
                  VisibilityMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              visibilityMap_.getMutableMap().put(
                  visibilityMap__.getKey(), visibilityMap__.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                typeKindMap_ = com.google.protobuf.MapField.newMapField(
                    TypeKindMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              typeKindMap__ = input.readMessage(
                  TypeKindMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              typeKindMap_.getMutableMap().put(
                  typeKindMap__.getKey(), typeKindMap__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                nameSpaceMap_ = com.google.protobuf.MapField.newMapField(
                    NameSpaceMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              nameSpaceMap__ = input.readMessage(
                  NameSpaceMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              nameSpaceMap_.getMutableMap().put(
                  nameSpaceMap__.getKey(), nameSpaceMap__.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                elementKindMap_ = com.google.protobuf.MapField.newMapField(
                    ElementKindMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              elementKindMap__ = input.readMessage(
                  ElementKindMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              elementKindMap_.getMutableMap().put(
                  elementKindMap__.getKey(), elementKindMap__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              sha_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetVisibilityMap();
        case 2:
          return internalGetTypeKindMap();
        case 3:
          return internalGetNameSpaceMap();
        case 4:
          return internalGetElementKindMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.class, com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.Builder.class);
    }

    public static final int SHA_FIELD_NUMBER = 5;
    private volatile java.lang.Object sha_;
    /**
     * <code>string sha = 5;</code>
     * @return The sha.
     */
    public java.lang.String getSha() {
      java.lang.Object ref = sha_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sha_ = s;
        return s;
      }
    }
    /**
     * <code>string sha = 5;</code>
     * @return The bytes for sha.
     */
    public com.google.protobuf.ByteString
        getShaBytes() {
      java.lang.Object ref = sha_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VISIBILITYMAP_FIELD_NUMBER = 1;
    private static final class VisibilityMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_VisibilityMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> visibilityMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetVisibilityMap() {
      if (visibilityMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VisibilityMapDefaultEntryHolder.defaultEntry);
      }
      return visibilityMap_;
    }

    public int getVisibilityMapCount() {
      return internalGetVisibilityMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    public boolean containsVisibilityMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetVisibilityMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVisibilityMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getVisibilityMap() {
      return getVisibilityMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getVisibilityMapMap() {
      return internalGetVisibilityMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    public int getVisibilityMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetVisibilityMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
     */

    public int getVisibilityMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetVisibilityMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TYPEKINDMAP_FIELD_NUMBER = 2;
    private static final class TypeKindMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_TypeKindMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> typeKindMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetTypeKindMap() {
      if (typeKindMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TypeKindMapDefaultEntryHolder.defaultEntry);
      }
      return typeKindMap_;
    }

    public int getTypeKindMapCount() {
      return internalGetTypeKindMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    public boolean containsTypeKindMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTypeKindMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTypeKindMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getTypeKindMap() {
      return getTypeKindMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getTypeKindMapMap() {
      return internalGetTypeKindMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    public int getTypeKindMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetTypeKindMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
     */

    public int getTypeKindMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetTypeKindMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int NAMESPACEMAP_FIELD_NUMBER = 3;
    private static final class NameSpaceMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_NameSpaceMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> nameSpaceMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetNameSpaceMap() {
      if (nameSpaceMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NameSpaceMapDefaultEntryHolder.defaultEntry);
      }
      return nameSpaceMap_;
    }

    public int getNameSpaceMapCount() {
      return internalGetNameSpaceMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    public boolean containsNameSpaceMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetNameSpaceMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNameSpaceMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getNameSpaceMap() {
      return getNameSpaceMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getNameSpaceMapMap() {
      return internalGetNameSpaceMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    public int getNameSpaceMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetNameSpaceMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
     */

    public int getNameSpaceMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetNameSpaceMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int ELEMENTKINDMAP_FIELD_NUMBER = 4;
    private static final class ElementKindMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_ElementKindMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> elementKindMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetElementKindMap() {
      if (elementKindMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ElementKindMapDefaultEntryHolder.defaultEntry);
      }
      return elementKindMap_;
    }

    public int getElementKindMapCount() {
      return internalGetElementKindMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    public boolean containsElementKindMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetElementKindMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getElementKindMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getElementKindMap() {
      return getElementKindMapMap();
    }
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getElementKindMapMap() {
      return internalGetElementKindMap().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    public int getElementKindMapOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetElementKindMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
     */

    public int getElementKindMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetElementKindMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetVisibilityMap(),
          VisibilityMapDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTypeKindMap(),
          TypeKindMapDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetNameSpaceMap(),
          NameSpaceMapDefaultEntryHolder.defaultEntry,
          3);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetElementKindMap(),
          ElementKindMapDefaultEntryHolder.defaultEntry,
          4);
      if (!getShaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sha_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetVisibilityMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        visibilityMap__ = VisibilityMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, visibilityMap__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetTypeKindMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        typeKindMap__ = TypeKindMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, typeKindMap__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetNameSpaceMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        nameSpaceMap__ = NameSpaceMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, nameSpaceMap__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetElementKindMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        elementKindMap__ = ElementKindMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, elementKindMap__);
      }
      if (!getShaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sha_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld)) {
        return super.equals(obj);
      }
      com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld other = (com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld) obj;

      if (!getSha()
          .equals(other.getSha())) return false;
      if (!internalGetVisibilityMap().equals(
          other.internalGetVisibilityMap())) return false;
      if (!internalGetTypeKindMap().equals(
          other.internalGetTypeKindMap())) return false;
      if (!internalGetNameSpaceMap().equals(
          other.internalGetNameSpaceMap())) return false;
      if (!internalGetElementKindMap().equals(
          other.internalGetElementKindMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SHA_FIELD_NUMBER;
      hash = (53 * hash) + getSha().hashCode();
      if (!internalGetVisibilityMap().getMap().isEmpty()) {
        hash = (37 * hash) + VISIBILITYMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetVisibilityMap().hashCode();
      }
      if (!internalGetTypeKindMap().getMap().isEmpty()) {
        hash = (37 * hash) + TYPEKINDMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTypeKindMap().hashCode();
      }
      if (!internalGetNameSpaceMap().getMap().isEmpty()) {
        hash = (37 * hash) + NAMESPACEMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNameSpaceMap().hashCode();
      }
      if (!internalGetElementKindMap().getMap().isEmpty()) {
        hash = (37 * hash) + ELEMENTKINDMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetElementKindMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TheWorld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TheWorld)
        com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetVisibilityMap();
          case 2:
            return internalGetTypeKindMap();
          case 3:
            return internalGetNameSpaceMap();
          case 4:
            return internalGetElementKindMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableVisibilityMap();
          case 2:
            return internalGetMutableTypeKindMap();
          case 3:
            return internalGetMutableNameSpaceMap();
          case 4:
            return internalGetMutableElementKindMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.class, com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.Builder.class);
      }

      // Construct using com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sha_ = "";

        internalGetMutableVisibilityMap().clear();
        internalGetMutableTypeKindMap().clear();
        internalGetMutableNameSpaceMap().clear();
        internalGetMutableElementKindMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.refactorings.TheWorldOuterClass.internal_static_TheWorld_descriptor;
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld getDefaultInstanceForType() {
        return com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.getDefaultInstance();
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld build() {
        com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld buildPartial() {
        com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld result = new com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld(this);
        int from_bitField0_ = bitField0_;
        result.sha_ = sha_;
        result.visibilityMap_ = internalGetVisibilityMap();
        result.visibilityMap_.makeImmutable();
        result.typeKindMap_ = internalGetTypeKindMap();
        result.typeKindMap_.makeImmutable();
        result.nameSpaceMap_ = internalGetNameSpaceMap();
        result.nameSpaceMap_.makeImmutable();
        result.elementKindMap_ = internalGetElementKindMap();
        result.elementKindMap_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld) {
          return mergeFrom((com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld other) {
        if (other == com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld.getDefaultInstance()) return this;
        if (!other.getSha().isEmpty()) {
          sha_ = other.sha_;
          onChanged();
        }
        internalGetMutableVisibilityMap().mergeFrom(
            other.internalGetVisibilityMap());
        internalGetMutableTypeKindMap().mergeFrom(
            other.internalGetTypeKindMap());
        internalGetMutableNameSpaceMap().mergeFrom(
            other.internalGetNameSpaceMap());
        internalGetMutableElementKindMap().mergeFrom(
            other.internalGetElementKindMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sha_ = "";
      /**
       * <code>string sha = 5;</code>
       * @return The sha.
       */
      public java.lang.String getSha() {
        java.lang.Object ref = sha_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sha_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sha = 5;</code>
       * @return The bytes for sha.
       */
      public com.google.protobuf.ByteString
          getShaBytes() {
        java.lang.Object ref = sha_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sha = 5;</code>
       * @param value The sha to set.
       * @return This builder for chaining.
       */
      public Builder setSha(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sha = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSha() {
        
        sha_ = getDefaultInstance().getSha();
        onChanged();
        return this;
      }
      /**
       * <code>string sha = 5;</code>
       * @param value The bytes for sha to set.
       * @return This builder for chaining.
       */
      public Builder setShaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sha_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> visibilityMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetVisibilityMap() {
        if (visibilityMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              VisibilityMapDefaultEntryHolder.defaultEntry);
        }
        return visibilityMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableVisibilityMap() {
        onChanged();;
        if (visibilityMap_ == null) {
          visibilityMap_ = com.google.protobuf.MapField.newMapField(
              VisibilityMapDefaultEntryHolder.defaultEntry);
        }
        if (!visibilityMap_.isMutable()) {
          visibilityMap_ = visibilityMap_.copy();
        }
        return visibilityMap_;
      }

      public int getVisibilityMapCount() {
        return internalGetVisibilityMap().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public boolean containsVisibilityMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetVisibilityMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getVisibilityMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getVisibilityMap() {
        return getVisibilityMapMap();
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getVisibilityMapMap() {
        return internalGetVisibilityMap().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public int getVisibilityMapOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetVisibilityMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public int getVisibilityMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetVisibilityMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearVisibilityMap() {
        internalGetMutableVisibilityMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public Builder removeVisibilityMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableVisibilityMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableVisibilityMap() {
        return internalGetMutableVisibilityMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */
      public Builder putVisibilityMap(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableVisibilityMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; visibilityMap = 1;</code>
       */

      public Builder putAllVisibilityMap(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableVisibilityMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> typeKindMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetTypeKindMap() {
        if (typeKindMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TypeKindMapDefaultEntryHolder.defaultEntry);
        }
        return typeKindMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableTypeKindMap() {
        onChanged();;
        if (typeKindMap_ == null) {
          typeKindMap_ = com.google.protobuf.MapField.newMapField(
              TypeKindMapDefaultEntryHolder.defaultEntry);
        }
        if (!typeKindMap_.isMutable()) {
          typeKindMap_ = typeKindMap_.copy();
        }
        return typeKindMap_;
      }

      public int getTypeKindMapCount() {
        return internalGetTypeKindMap().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public boolean containsTypeKindMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTypeKindMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTypeKindMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getTypeKindMap() {
        return getTypeKindMapMap();
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getTypeKindMapMap() {
        return internalGetTypeKindMap().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public int getTypeKindMapOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetTypeKindMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public int getTypeKindMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetTypeKindMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTypeKindMap() {
        internalGetMutableTypeKindMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public Builder removeTypeKindMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTypeKindMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableTypeKindMap() {
        return internalGetMutableTypeKindMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */
      public Builder putTypeKindMap(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableTypeKindMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; typeKindMap = 2;</code>
       */

      public Builder putAllTypeKindMap(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableTypeKindMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> nameSpaceMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetNameSpaceMap() {
        if (nameSpaceMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NameSpaceMapDefaultEntryHolder.defaultEntry);
        }
        return nameSpaceMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableNameSpaceMap() {
        onChanged();;
        if (nameSpaceMap_ == null) {
          nameSpaceMap_ = com.google.protobuf.MapField.newMapField(
              NameSpaceMapDefaultEntryHolder.defaultEntry);
        }
        if (!nameSpaceMap_.isMutable()) {
          nameSpaceMap_ = nameSpaceMap_.copy();
        }
        return nameSpaceMap_;
      }

      public int getNameSpaceMapCount() {
        return internalGetNameSpaceMap().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public boolean containsNameSpaceMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetNameSpaceMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNameSpaceMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getNameSpaceMap() {
        return getNameSpaceMapMap();
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getNameSpaceMapMap() {
        return internalGetNameSpaceMap().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public int getNameSpaceMapOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetNameSpaceMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public int getNameSpaceMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetNameSpaceMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearNameSpaceMap() {
        internalGetMutableNameSpaceMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public Builder removeNameSpaceMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableNameSpaceMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableNameSpaceMap() {
        return internalGetMutableNameSpaceMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */
      public Builder putNameSpaceMap(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableNameSpaceMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; nameSpaceMap = 3;</code>
       */

      public Builder putAllNameSpaceMap(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableNameSpaceMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> elementKindMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetElementKindMap() {
        if (elementKindMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ElementKindMapDefaultEntryHolder.defaultEntry);
        }
        return elementKindMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableElementKindMap() {
        onChanged();;
        if (elementKindMap_ == null) {
          elementKindMap_ = com.google.protobuf.MapField.newMapField(
              ElementKindMapDefaultEntryHolder.defaultEntry);
        }
        if (!elementKindMap_.isMutable()) {
          elementKindMap_ = elementKindMap_.copy();
        }
        return elementKindMap_;
      }

      public int getElementKindMapCount() {
        return internalGetElementKindMap().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public boolean containsElementKindMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetElementKindMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getElementKindMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getElementKindMap() {
        return getElementKindMapMap();
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getElementKindMapMap() {
        return internalGetElementKindMap().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public int getElementKindMapOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetElementKindMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public int getElementKindMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetElementKindMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearElementKindMap() {
        internalGetMutableElementKindMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public Builder removeElementKindMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableElementKindMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableElementKindMap() {
        return internalGetMutableElementKindMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */
      public Builder putElementKindMap(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableElementKindMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; elementKindMap = 4;</code>
       */

      public Builder putAllElementKindMap(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableElementKindMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TheWorld)
    }

    // @@protoc_insertion_point(class_scope:TheWorld)
    private static final com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld();
    }

    public static com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TheWorld>
        PARSER = new com.google.protobuf.AbstractParser<TheWorld>() {
      @java.lang.Override
      public TheWorld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TheWorld(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TheWorld> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TheWorld> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.t2r.common.models.refactorings.TheWorldOuterClass.TheWorld getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheWorld_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheWorld_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheWorld_VisibilityMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheWorld_VisibilityMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheWorld_TypeKindMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheWorld_TypeKindMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheWorld_NameSpaceMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheWorld_NameSpaceMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TheWorld_ElementKindMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TheWorld_ElementKindMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TheWorld.proto\"\275\003\n\010TheWorld\022\013\n\003sha\030\005 \001" +
      "(\t\0223\n\rvisibilityMap\030\001 \003(\0132\034.TheWorld.Vis" +
      "ibilityMapEntry\022/\n\013typeKindMap\030\002 \003(\0132\032.T" +
      "heWorld.TypeKindMapEntry\0221\n\014nameSpaceMap" +
      "\030\003 \003(\0132\033.TheWorld.NameSpaceMapEntry\0225\n\016e" +
      "lementKindMap\030\004 \003(\0132\035.TheWorld.ElementKi" +
      "ndMapEntry\0324\n\022VisibilityMapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\0322\n\020TypeKindMapE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\0323\n\021" +
      "NameSpaceMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\005:\0028\001\0325\n\023ElementKindMapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001B$\n\"com.t2r.comm" +
      "on.models.refactoringsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TheWorld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TheWorld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheWorld_descriptor,
        new java.lang.String[] { "Sha", "VisibilityMap", "TypeKindMap", "NameSpaceMap", "ElementKindMap", });
    internal_static_TheWorld_VisibilityMapEntry_descriptor =
      internal_static_TheWorld_descriptor.getNestedTypes().get(0);
    internal_static_TheWorld_VisibilityMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheWorld_VisibilityMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TheWorld_TypeKindMapEntry_descriptor =
      internal_static_TheWorld_descriptor.getNestedTypes().get(1);
    internal_static_TheWorld_TypeKindMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheWorld_TypeKindMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TheWorld_NameSpaceMapEntry_descriptor =
      internal_static_TheWorld_descriptor.getNestedTypes().get(2);
    internal_static_TheWorld_NameSpaceMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheWorld_NameSpaceMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TheWorld_ElementKindMapEntry_descriptor =
      internal_static_TheWorld_descriptor.getNestedTypes().get(3);
    internal_static_TheWorld_ElementKindMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TheWorld_ElementKindMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
